[project]
name = "russian_latiniser"
version = "0.0.1"
authors = [
  { name="Kanzor", email=" " },
]
description = "A small package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU GPLv3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/timashovboris/RussianLatiniser"
"Bug Tracker" = "https://github.com/timashovboris/RussianLatiniser/issues"